DOMAIN = "enablebanking"
API_BASE = "https://api.enablebanking.com"
PRIVATE_KEY_PATH = "/config/enablebanking/private.key"
SESSIONS_PATH = "/config/enablebanking/sessions.json"
DB_PATH = "/config/enablebanking/transactions.db"
CONF_APP_ID = "app_id"
CONF_SENSORS = "sensors"
CONF_TRANSACTION_INTERVAL = "transaction_interval"
CONF_BALANCE_INTERVAL = "balance_interval"
DEFAULT_TRANSACTION_INTERVAL = 720   # 12 hours — max 2 calls per day
DEFAULT_BALANCE_INTERVAL = 1440      # 24 hours — 1 call per day
